openapi: "3.0.3"
info:
  title: Petstore API
  version: "1.0.0"
  description: A sample API for managing a pet store.
servers:
  - url: https://petstore.example.com/api/v1
security:
  - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Pet:
      type: object
      required: [name, species]
      properties:
        id:
          type: integer
          description: Unique pet ID
        name:
          type: string
          description: Pet name
        species:
          type: string
          enum: [dog, cat, bird, fish, reptile]
          description: Species
        breed:
          type: string
          description: Breed or variety
        age:
          type: integer
          description: Age in years
        status:
          type: string
          enum: [available, pending, adopted]
          description: Adoption status
    Owner:
      type: object
      required: [name, email]
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      description: Returns a paginated list of pets with optional filtering.
      tags: [pets]
      parameters:
        - name: species
          in: query
          schema:
            type: string
            enum: [dog, cat, bird, fish, reptile]
          description: Filter by species
        - name: status
          in: query
          schema:
            type: string
            enum: [available, pending, adopted]
          description: Filter by adoption status
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          description: Max results per page
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Pagination offset
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
    post:
      operationId: createPet
      summary: Add a new pet
      tags: [pets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "201":
          description: Pet created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /pets/{petId}:
    get:
      operationId: getPet
      summary: Get a pet by ID
      tags: [pets]
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pet details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "404":
          description: Pet not found
    put:
      operationId: updatePet
      summary: Update a pet
      tags: [pets]
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    delete:
      operationId: deletePet
      summary: Delete a pet
      tags: [pets]
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Pet deleted
  /pets/{petId}/adopt:
    post:
      operationId: adoptPet
      summary: Mark a pet as adopted
      tags: [pets]
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [owner_id]
              properties:
                owner_id:
                  type: integer
                  description: ID of the adopting owner
                notes:
                  type: string
                  description: Adoption notes
      responses:
        "200":
          description: Pet adopted
  /pets/search:
    get:
      operationId: searchPets
      summary: Search pets by keyword
      tags: [pets]
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: Search query
        - name: species
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
  /owners:
    get:
      operationId: listOwners
      summary: List all owners
      tags: [owners]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Owner list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Owner"
    post:
      operationId: createOwner
      summary: Register a new owner
      tags: [owners]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Owner"
      responses:
        "201":
          description: Owner created
  /owners/{ownerId}:
    get:
      operationId: getOwner
      summary: Get owner details
      tags: [owners]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Owner details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Owner"
    delete:
      operationId: deleteOwner
      summary: Delete an owner record
      tags: [owners]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Owner deleted
  /owners/{ownerId}/pets:
    get:
      operationId: listOwnerPets
      summary: List pets owned by a specific owner
      tags: [owners]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pets belonging to this owner
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
